// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"gitlab.top.slotssprite.com/my/rpc-layout/internal/data/ent/player"
	"gitlab.top.slotssprite.com/my/rpc-layout/internal/data/ent/predicate"
)

// PlayerUpdate is the builder for updating Player entities.
type PlayerUpdate struct {
	config
	hooks    []Hook
	mutation *PlayerMutation
}

// Where appends a list predicates to the PlayerUpdate builder.
func (pu *PlayerUpdate) Where(ps ...predicate.Player) *PlayerUpdate {
	pu.mutation.Where(ps...)
	return pu
}

// SetAccountID sets the "account_id" field.
func (pu *PlayerUpdate) SetAccountID(i int64) *PlayerUpdate {
	pu.mutation.ResetAccountID()
	pu.mutation.SetAccountID(i)
	return pu
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (pu *PlayerUpdate) SetNillableAccountID(i *int64) *PlayerUpdate {
	if i != nil {
		pu.SetAccountID(*i)
	}
	return pu
}

// AddAccountID adds i to the "account_id" field.
func (pu *PlayerUpdate) AddAccountID(i int64) *PlayerUpdate {
	pu.mutation.AddAccountID(i)
	return pu
}

// SetPlayerID sets the "player_id" field.
func (pu *PlayerUpdate) SetPlayerID(i int64) *PlayerUpdate {
	pu.mutation.ResetPlayerID()
	pu.mutation.SetPlayerID(i)
	return pu
}

// SetNillablePlayerID sets the "player_id" field if the given value is not nil.
func (pu *PlayerUpdate) SetNillablePlayerID(i *int64) *PlayerUpdate {
	if i != nil {
		pu.SetPlayerID(*i)
	}
	return pu
}

// AddPlayerID adds i to the "player_id" field.
func (pu *PlayerUpdate) AddPlayerID(i int64) *PlayerUpdate {
	pu.mutation.AddPlayerID(i)
	return pu
}

// SetNickname sets the "nickname" field.
func (pu *PlayerUpdate) SetNickname(s string) *PlayerUpdate {
	pu.mutation.SetNickname(s)
	return pu
}

// SetNillableNickname sets the "nickname" field if the given value is not nil.
func (pu *PlayerUpdate) SetNillableNickname(s *string) *PlayerUpdate {
	if s != nil {
		pu.SetNickname(*s)
	}
	return pu
}

// ClearNickname clears the value of the "nickname" field.
func (pu *PlayerUpdate) ClearNickname() *PlayerUpdate {
	pu.mutation.ClearNickname()
	return pu
}

// SetGender sets the "gender" field.
func (pu *PlayerUpdate) SetGender(i int32) *PlayerUpdate {
	pu.mutation.ResetGender()
	pu.mutation.SetGender(i)
	return pu
}

// SetNillableGender sets the "gender" field if the given value is not nil.
func (pu *PlayerUpdate) SetNillableGender(i *int32) *PlayerUpdate {
	if i != nil {
		pu.SetGender(*i)
	}
	return pu
}

// AddGender adds i to the "gender" field.
func (pu *PlayerUpdate) AddGender(i int32) *PlayerUpdate {
	pu.mutation.AddGender(i)
	return pu
}

// ClearGender clears the value of the "gender" field.
func (pu *PlayerUpdate) ClearGender() *PlayerUpdate {
	pu.mutation.ClearGender()
	return pu
}

// SetAvatar sets the "avatar" field.
func (pu *PlayerUpdate) SetAvatar(s string) *PlayerUpdate {
	pu.mutation.SetAvatar(s)
	return pu
}

// SetNillableAvatar sets the "avatar" field if the given value is not nil.
func (pu *PlayerUpdate) SetNillableAvatar(s *string) *PlayerUpdate {
	if s != nil {
		pu.SetAvatar(*s)
	}
	return pu
}

// ClearAvatar clears the value of the "avatar" field.
func (pu *PlayerUpdate) ClearAvatar() *PlayerUpdate {
	pu.mutation.ClearAvatar()
	return pu
}

// Mutation returns the PlayerMutation object of the builder.
func (pu *PlayerUpdate) Mutation() *PlayerMutation {
	return pu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (pu *PlayerUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, pu.sqlSave, pu.mutation, pu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (pu *PlayerUpdate) SaveX(ctx context.Context) int {
	affected, err := pu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (pu *PlayerUpdate) Exec(ctx context.Context) error {
	_, err := pu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pu *PlayerUpdate) ExecX(ctx context.Context) {
	if err := pu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (pu *PlayerUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(player.Table, player.Columns, sqlgraph.NewFieldSpec(player.FieldID, field.TypeInt64))
	if ps := pu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := pu.mutation.AccountID(); ok {
		_spec.SetField(player.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := pu.mutation.AddedAccountID(); ok {
		_spec.AddField(player.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := pu.mutation.PlayerID(); ok {
		_spec.SetField(player.FieldPlayerID, field.TypeInt64, value)
	}
	if value, ok := pu.mutation.AddedPlayerID(); ok {
		_spec.AddField(player.FieldPlayerID, field.TypeInt64, value)
	}
	if value, ok := pu.mutation.Nickname(); ok {
		_spec.SetField(player.FieldNickname, field.TypeString, value)
	}
	if pu.mutation.NicknameCleared() {
		_spec.ClearField(player.FieldNickname, field.TypeString)
	}
	if value, ok := pu.mutation.Gender(); ok {
		_spec.SetField(player.FieldGender, field.TypeInt32, value)
	}
	if value, ok := pu.mutation.AddedGender(); ok {
		_spec.AddField(player.FieldGender, field.TypeInt32, value)
	}
	if pu.mutation.GenderCleared() {
		_spec.ClearField(player.FieldGender, field.TypeInt32)
	}
	if value, ok := pu.mutation.Avatar(); ok {
		_spec.SetField(player.FieldAvatar, field.TypeString, value)
	}
	if pu.mutation.AvatarCleared() {
		_spec.ClearField(player.FieldAvatar, field.TypeString)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, pu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{player.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	pu.mutation.done = true
	return n, nil
}

// PlayerUpdateOne is the builder for updating a single Player entity.
type PlayerUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PlayerMutation
}

// SetAccountID sets the "account_id" field.
func (puo *PlayerUpdateOne) SetAccountID(i int64) *PlayerUpdateOne {
	puo.mutation.ResetAccountID()
	puo.mutation.SetAccountID(i)
	return puo
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (puo *PlayerUpdateOne) SetNillableAccountID(i *int64) *PlayerUpdateOne {
	if i != nil {
		puo.SetAccountID(*i)
	}
	return puo
}

// AddAccountID adds i to the "account_id" field.
func (puo *PlayerUpdateOne) AddAccountID(i int64) *PlayerUpdateOne {
	puo.mutation.AddAccountID(i)
	return puo
}

// SetPlayerID sets the "player_id" field.
func (puo *PlayerUpdateOne) SetPlayerID(i int64) *PlayerUpdateOne {
	puo.mutation.ResetPlayerID()
	puo.mutation.SetPlayerID(i)
	return puo
}

// SetNillablePlayerID sets the "player_id" field if the given value is not nil.
func (puo *PlayerUpdateOne) SetNillablePlayerID(i *int64) *PlayerUpdateOne {
	if i != nil {
		puo.SetPlayerID(*i)
	}
	return puo
}

// AddPlayerID adds i to the "player_id" field.
func (puo *PlayerUpdateOne) AddPlayerID(i int64) *PlayerUpdateOne {
	puo.mutation.AddPlayerID(i)
	return puo
}

// SetNickname sets the "nickname" field.
func (puo *PlayerUpdateOne) SetNickname(s string) *PlayerUpdateOne {
	puo.mutation.SetNickname(s)
	return puo
}

// SetNillableNickname sets the "nickname" field if the given value is not nil.
func (puo *PlayerUpdateOne) SetNillableNickname(s *string) *PlayerUpdateOne {
	if s != nil {
		puo.SetNickname(*s)
	}
	return puo
}

// ClearNickname clears the value of the "nickname" field.
func (puo *PlayerUpdateOne) ClearNickname() *PlayerUpdateOne {
	puo.mutation.ClearNickname()
	return puo
}

// SetGender sets the "gender" field.
func (puo *PlayerUpdateOne) SetGender(i int32) *PlayerUpdateOne {
	puo.mutation.ResetGender()
	puo.mutation.SetGender(i)
	return puo
}

// SetNillableGender sets the "gender" field if the given value is not nil.
func (puo *PlayerUpdateOne) SetNillableGender(i *int32) *PlayerUpdateOne {
	if i != nil {
		puo.SetGender(*i)
	}
	return puo
}

// AddGender adds i to the "gender" field.
func (puo *PlayerUpdateOne) AddGender(i int32) *PlayerUpdateOne {
	puo.mutation.AddGender(i)
	return puo
}

// ClearGender clears the value of the "gender" field.
func (puo *PlayerUpdateOne) ClearGender() *PlayerUpdateOne {
	puo.mutation.ClearGender()
	return puo
}

// SetAvatar sets the "avatar" field.
func (puo *PlayerUpdateOne) SetAvatar(s string) *PlayerUpdateOne {
	puo.mutation.SetAvatar(s)
	return puo
}

// SetNillableAvatar sets the "avatar" field if the given value is not nil.
func (puo *PlayerUpdateOne) SetNillableAvatar(s *string) *PlayerUpdateOne {
	if s != nil {
		puo.SetAvatar(*s)
	}
	return puo
}

// ClearAvatar clears the value of the "avatar" field.
func (puo *PlayerUpdateOne) ClearAvatar() *PlayerUpdateOne {
	puo.mutation.ClearAvatar()
	return puo
}

// Mutation returns the PlayerMutation object of the builder.
func (puo *PlayerUpdateOne) Mutation() *PlayerMutation {
	return puo.mutation
}

// Where appends a list predicates to the PlayerUpdate builder.
func (puo *PlayerUpdateOne) Where(ps ...predicate.Player) *PlayerUpdateOne {
	puo.mutation.Where(ps...)
	return puo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (puo *PlayerUpdateOne) Select(field string, fields ...string) *PlayerUpdateOne {
	puo.fields = append([]string{field}, fields...)
	return puo
}

// Save executes the query and returns the updated Player entity.
func (puo *PlayerUpdateOne) Save(ctx context.Context) (*Player, error) {
	return withHooks(ctx, puo.sqlSave, puo.mutation, puo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (puo *PlayerUpdateOne) SaveX(ctx context.Context) *Player {
	node, err := puo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (puo *PlayerUpdateOne) Exec(ctx context.Context) error {
	_, err := puo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (puo *PlayerUpdateOne) ExecX(ctx context.Context) {
	if err := puo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (puo *PlayerUpdateOne) sqlSave(ctx context.Context) (_node *Player, err error) {
	_spec := sqlgraph.NewUpdateSpec(player.Table, player.Columns, sqlgraph.NewFieldSpec(player.FieldID, field.TypeInt64))
	id, ok := puo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Player.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := puo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, player.FieldID)
		for _, f := range fields {
			if !player.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != player.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := puo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := puo.mutation.AccountID(); ok {
		_spec.SetField(player.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := puo.mutation.AddedAccountID(); ok {
		_spec.AddField(player.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := puo.mutation.PlayerID(); ok {
		_spec.SetField(player.FieldPlayerID, field.TypeInt64, value)
	}
	if value, ok := puo.mutation.AddedPlayerID(); ok {
		_spec.AddField(player.FieldPlayerID, field.TypeInt64, value)
	}
	if value, ok := puo.mutation.Nickname(); ok {
		_spec.SetField(player.FieldNickname, field.TypeString, value)
	}
	if puo.mutation.NicknameCleared() {
		_spec.ClearField(player.FieldNickname, field.TypeString)
	}
	if value, ok := puo.mutation.Gender(); ok {
		_spec.SetField(player.FieldGender, field.TypeInt32, value)
	}
	if value, ok := puo.mutation.AddedGender(); ok {
		_spec.AddField(player.FieldGender, field.TypeInt32, value)
	}
	if puo.mutation.GenderCleared() {
		_spec.ClearField(player.FieldGender, field.TypeInt32)
	}
	if value, ok := puo.mutation.Avatar(); ok {
		_spec.SetField(player.FieldAvatar, field.TypeString, value)
	}
	if puo.mutation.AvatarCleared() {
		_spec.ClearField(player.FieldAvatar, field.TypeString)
	}
	_node = &Player{config: puo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, puo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{player.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	puo.mutation.done = true
	return _node, nil
}
