// Code generated by ent, DO NOT EDIT.

package ent

import (
	"gitlab.top.slotssprite.com/my/rpc-layout/internal/data/ent/account"
	"gitlab.top.slotssprite.com/my/rpc-layout/internal/data/ent/player"
	"gitlab.top.slotssprite.com/my/rpc-layout/internal/data/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	accountFields := schema.Account{}.Fields()
	_ = accountFields
	// accountDescEmail is the schema descriptor for email field.
	accountDescEmail := accountFields[2].Descriptor()
	// account.DefaultEmail holds the default value on creation for the email field.
	account.DefaultEmail = accountDescEmail.Default.(string)
	// accountDescPhone is the schema descriptor for phone field.
	accountDescPhone := accountFields[3].Descriptor()
	// account.DefaultPhone holds the default value on creation for the phone field.
	account.DefaultPhone = accountDescPhone.Default.(string)
	playerFields := schema.Player{}.Fields()
	_ = playerFields
	// playerDescGender is the schema descriptor for gender field.
	playerDescGender := playerFields[4].Descriptor()
	// player.DefaultGender holds the default value on creation for the gender field.
	player.DefaultGender = playerDescGender.Default.(int32)
}
