// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AccountColumns holds the columns for the "account" table.
	AccountColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true, SchemaType: map[string]string{"mysql": "bigint"}},
		{Name: "pass", Type: field.TypeString, Nullable: true, SchemaType: map[string]string{"mysql": "varchar(100)"}},
		{Name: "email", Type: field.TypeString, Nullable: true, Default: "", SchemaType: map[string]string{"mysql": "varchar(128)"}},
		{Name: "phone", Type: field.TypeString, Nullable: true, Default: "", SchemaType: map[string]string{"mysql": "varchar(20)"}},
	}
	// AccountTable holds the schema information for the "account" table.
	AccountTable = &schema.Table{
		Name:       "account",
		Columns:    AccountColumns,
		PrimaryKey: []*schema.Column{AccountColumns[0]},
	}
	// PlayerColumns holds the columns for the "player" table.
	PlayerColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true, SchemaType: map[string]string{"mysql": "bigint"}},
		{Name: "account_id", Type: field.TypeInt64, SchemaType: map[string]string{"mysql": "bigint"}},
		{Name: "player_id", Type: field.TypeInt64, SchemaType: map[string]string{"mysql": "bigint"}},
		{Name: "nickname", Type: field.TypeString, Nullable: true, SchemaType: map[string]string{"mysql": "varchar(64)"}},
		{Name: "gender", Type: field.TypeInt32, Nullable: true, Default: 1, SchemaType: map[string]string{"mysql": "int"}},
		{Name: "avatar", Type: field.TypeString, Nullable: true, SchemaType: map[string]string{"mysql": "varchar(256)"}},
	}
	// PlayerTable holds the schema information for the "player" table.
	PlayerTable = &schema.Table{
		Name:       "player",
		Columns:    PlayerColumns,
		PrimaryKey: []*schema.Column{PlayerColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AccountTable,
		PlayerTable,
	}
)

func init() {
	AccountTable.Annotation = &entsql.Annotation{
		Table: "account",
	}
	PlayerTable.Annotation = &entsql.Annotation{
		Table: "player",
	}
}
